language: go

go:
    - 1.x
    - tip

go_import_path: github.com/ptt/pttweb

sudo: required
dist: bionic
addons:
    apt:
        update: true
        packages:
            - protobuf-compiler

install:
    - go get google.golang.org/grpc
    - go get -u github.com/golang/protobuf/{proto,protoc-gen-go}
    - make -C $GOPATH/src/github.com/ptt/pttweb/proto
    - go get -u -t -f github.com/ptt/pttweb/...
